FROM node:22-slim

RUN npm install -g pnpm@9.14.4

USER node
WORKDIR /app
COPY --chown=node:node . .

RUN pnpm install --frozen-lockfile
RUN pnpm --filter "@webstudio-is/cloudflare-publisher" build

EXPOSE 4000

WORKDIR /app/apps/cloudflare-publisher
CMD ["pnpm", "start"]
